
--PART:1 DB CREATE
CREATE DATABASE VIEW_DB;

USE VIEW_DB

--PART:2 TABLE CREATE
CREATE TABLE CRICKETER_DETAIL(
    CDID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20),
    DOB DATE,
    ROLE VARCHAR(50),
    HIGHEST_T20I_RUNS INT,
	CREATEDAT DATETIME DEFAULT GETDATE()
);

--PART:3 TWO ROW DATA INSERT
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('ROHIT','SHARMA','1987-04-30','Batter',121)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('VIRAT','KOHLI','1988-11-05','Batter',122)

--PART:4 DATA GET
SELECT * FROM CRICKETER_DETAIL;

--PART:5 VIWE CREATE 
CREATE VIEW VW_CRICKETER_DETAIL
AS 
SELECT CDID,FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS
FROM CRICKETER_DETAIL;

--PAERT:6 GET DATA FROM VIEW
SELECT * FROM VW_CRICKETER_DETAIL;


--PART:6.1 NEW VIEW CREATE BASED ON VW_CRICKETER_DETAIL THIS VIEW 
CREATE VIEW VW_SPECIFIC_COL_BASED_ON_EXIST_VIEW
AS
SELECT CDID,FIRST_NAME,LAST_NAME
FROM VW_CRICKETER_DETAIL;

SELECT 'CRICKETER_DETAIL' AS 'TABLE NAME',* FROM CRICKETER_DETAIL;
SELECT 'VW_CRICKETER_DETAIL' AS 'VIEW NAME',* FROM VW_CRICKETER_DETAIL;
SELECT 'VW_SPECIFIC_COL_BASED_ON_EXIST_VIEW'AS 'VIEW NAME',* FROM VW_SPECIFIC_COL_BASED_ON_EXIST_VIEW;


--PART:7 INSERT DATA IN VIEW 
INSERT INTO VW_CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('Yashasvi','Jaiswal','2001-12-28','Opening Batter',100)

--SO AUTO MATIC VIEW PE JO TABLE HAI USE ME DATA INSERT HOGA 
SELECT * FROM CRICKETER_DETAIL;	--FIRST_NAME: Yashasvi SEE THIS TABLE
SELECT * FROM VW_CRICKETER_DETAIL;

--PART:8 INSERT DATA IN VIEW FIRST_NAME NOT INSERT SO INSERT FAILS 
INSERT INTO CRICKETER_DETAIL(LAST_NAME,DOB,ROLE)
VALUES('Singh','1997-10-12','Middle-order Batter')

/*
Msg 515, Level 16, State 2, Line 4
Cannot insert the value NULL into column 'FIRST_NAME', table 'VIEW_DB.dbo.CRICKETER_DETAIL'; column does not allow nulls. INSERT fails.
*/

--PART:9 INSERT DATA IN VIEW FIRST_NAME INSERT BUT LAST_NAME NOT INSERT THIS CASE DATA INSERT 
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,DOB,ROLE)
VALUES('Rinku','1997-10-12','Middle-order Batter')

SELECT * FROM CRICKETER_DETAIL;	--FIRST_NAME:Rinku SEE THIS TABLE BUT LAST_NAME NULL
SELECT * FROM VW_CRICKETER_DETAIL;

--PART:10 FIRST_NAME:Rinku THIS ROW LAST_NAME UPDATE USING VIEW 
UPDATE VW_CRICKETER_DETAIL
SET LAST_NAME = 'Singh'
WHERE CDID = 5;

SELECT * FROM CRICKETER_DETAIL;	--LAST_NAME:Singh UPDATED
SELECT * FROM VW_CRICKETER_DETAIL;


--PART:11 FIRST_NAME:Rinku THIS ROW DELETE USING IN VIEW
DELETE FROM VW_CRICKETER_DETAIL WHERE CDID = 5;

SELECT * FROM CRICKETER_DETAIL;	--FIRST_NAME:Rinku ROW DELETED
SELECT * FROM VW_CRICKETER_DETAIL;

--PART:12 --TRIGGER APPLY ON VIEW
/*
	VIEW ONLY INSTEAD OF APPLY
*/
CREATE TRIGGER TRG_VW_CRICKETER_DETAIL
ON VW_CRICKETER_DETAIL
INSTEAD OF INSERT,UPDATE,DELETE 
AS 
BEGIN 
	SET NOCOUNT ON;
	
	PRINT 'VIEW:VW_CRICKETER_DETAIL NOT ALLOWED INSERT,UPDATE AND DELETE OPERATION.';
	
	ROLLBACK TRANSACTION;
END;
--GO 

--NOW INSERT DATA IN VIEW 
INSERT INTO VW_CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE)
VALUES('Rinku','Singh','1997-10-12','Middle-order Batter')

--ANS:
VIEW:VW_CRICKETER_DETAIL NOT ALLOWED INSERT,UPDATE AND DELETE OPERATION.
Msg 3609, Level 16, State 1, Line 1
The transaction ended in the trigger. The batch has been aborted.

--UPDATE DATA IN VIEW
UPDATE VW_CRICKETER_DETAIL
SET ROLE = 'Fighter Opening Batter'
WHERE CDID = 3;

--ANS:
VIEW:VW_CRICKETER_DETAIL NOT ALLOWED INSERT,UPDATE AND DELETE OPERATION.
Msg 3609, Level 16, State 1, Line 1
The transaction ended in the trigger. The batch has been aborted.

--DELETE DATA IN VIEW
DELETE FROM VW_CRICKETER_DETAIL
WHERE CDID = 3;

--ANS:
VIEW:VW_CRICKETER_DETAIL NOT ALLOWED INSERT,UPDATE AND DELETE OPERATION.
Msg 3609, Level 16, State 1, Line 1
The transaction ended in the trigger. The batch has been aborted.

--PART:13 MAIN TABLE DELETE 
DELETE FROM CRICKETER_DETAIL;

SELECT * FROM CRICKETER_DETAIL;	
SELECT * FROM VW_CRICKETER_DETAIL;


--SO MAIN TABLE AND VIEW BOTH DATA ARE DELETED.

--PART:14 NOW MAIN TABLE DATA INSERT 
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('ROHIT','SHARMA','1987-04-30','Batter',121)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('VIRAT','KOHLI','1988-11-05','Batter',122)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('Yashasvi','Jaiswal','2001-12-28','Opening Batter',100)

SELECT * FROM CRICKETER_DETAIL;	
SELECT * FROM VW_CRICKETER_DETAIL;


--PART:14 NOW MAIN TABLE DROP
DROP TABLE CRICKETER_DETAIL;

--MAIN TABLE CRICKETER_DETAIL DROP BUT VIEW EXISTS 

--SO THIS ISSUE SOLUTION WHENEVER TABLE DROP SO THIS TABLE DEPENDENT VIEW ALSO DROP
--SO NOW AGAIN ABOVE TABLE CREATED AND DATA FILL 
--NOW ABOVE PROBLEM SOLUTIO  USE BELOW SP 

CREATE TABLE CRICKETER_DETAIL(
    CDID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(20),
    DOB DATE,
    ROLE VARCHAR(50),
    HIGHEST_T20I_RUNS INT,
	CREATEDAT DATETIME DEFAULT GETDATE()
);

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('ROHIT','SHARMA','1987-04-30','Batter',121)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('VIRAT','KOHLI','1988-11-05','Batter',122)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('Yashasvi','Jaiswal','2001-12-28','Opening Batter',100)

SELECT * FROM CRICKETER_DETAIL;	
SELECT * FROM VW_CRICKETER_DETAIL;



CREATE PROCEDURE SP_DROP_TABLE_WITH_VIEWS
    @TableName SYSNAME
AS
BEGIN
    DECLARE @sql NVARCHAR(MAX) = '';

    -- Drop dependent views first
    SELECT @sql = @sql + 'DROP VIEW ' 
        + QUOTENAME(SCHEMA_NAME(v.schema_id)) 
        + '.' + QUOTENAME(v.name) + ';' + CHAR(13)
    FROM sys.views v
    INNER JOIN sys.sql_expression_dependencies d 
        ON v.object_id = d.referencing_id
    WHERE d.referenced_entity_name = @TableName;

    EXEC sp_executesql @sql;

    -- Drop table
    SET @sql = 'DROP TABLE ' + QUOTENAME(@TableName);
    EXEC sp_executesql @sql;
END;

--CALL SP
EXEC SP_DROP_TABLE_WITH_VIEWS 'CRICKETER_DETAIL'

--NOW 1ST VIEW DROP AND AFTER MAIN TABLE DROP 

---------------------------------------------

QUE: What is a View in SQL Server?
ANS:
--One type of sql query.
--Views as virtual tables.
--Views do not store any data physically by default.

QUE: What are the differences between a table and a view in SQL Server?
ANS:
/*
--The table is physical whereas the view is logical or virtual.
--A Table is an independent object whereas a view is a dependent object that is a view depends on the table or tables from which it is loading the data.
--When a new table is created from an existing table the new and old tables are independent themselves that is the changes of one table will not be reflected into the other table 
whereas if a view is created based on a table any changes that are performed on the table reflects into the view and any changes performed on the view reflected in the table also.
*/

QUE: How many types of views are there in SQL Server?
ANS:
--There are two types of views in SQL Server, they are
--[1] Simple Views
--[2] Complex Views

--Simple Views MEANS ONLY ONE TABLE USE.
--Complex Views MEANS MORE THAN ONE TABLE USE.