DECLARE @SOURCE_JSON VARCHAR(MAX) =' 
[
  {
    "ID":1,
    "FIRST_NAME": "ROHIT",
    "LAST_NAME": "SHARMA",
    "DOB": "1987-04-30",
    "ROLE": "Batter",
    "HIGHEST_T20I_RUNS": 121
  },
  {
    "ID":2,
    "FIRST_NAME": "VIRAT",
    "LAST_NAME": "KOHLI",
    "DOB": "1988-11-05",
    "ROLE": "Batter",
    "HIGHEST_T20I_RUNS": 122
  },
  
  {
    "ID":10,
    "FIRST_NAME": "Abhishek",
    "LAST_NAME": "Sharma",
    "DOB": "2000-09-04",
    "ROLE": "Batting All-rounder",
    "HIGHEST_T20I_RUNS": 100
  },
  {
    "ID":11,
    "FIRST_NAME": "Yashasvi",
    "LAST_NAME": "Jaiswal",
    "DOB": "2001-12-28",
    "ROLE": "Opening Batter",
    "HIGHEST_T20I_RUNS": 100
  },
  { 
    "ID":12,
    "FIRST_NAME": "Rinku",
    "LAST_NAME": "Singh",
    "DOB": "1997-10-12",
    "ROLE": "Middle-order Batter",
    "HIGHEST_T20I_RUNS": 69
  },
  {
    "ID":13,
    "FIRST_NAME": "Axar",
    "LAST_NAME": "Patel",
    "DOB": "1994-01-20",
    "ROLE": "All-rounder",
    "HIGHEST_T20I_RUNS": 65
  }
]'

 
DROP TABLE IF EXISTS #SOURCE;

CREATE TABLE #SOURCE(
    ID INT,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    DOB DATE,
    ROLE VARCHAR(50),
    HIGHEST_T20I_RUNS INT
);

INSERT INTO #SOURCE(ID,FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
SELECT 
    TRY_CAST(ID AS INT),
    FIRST_NAME,
    LAST_NAME,
    TRY_CAST(DOB AS DATE),
    ROLE,
    TRY_CAST(HIGHEST_T20I_RUNS AS INT)
FROM OPENJSON(@SOURCE_JSON)
WITH(
    ID VARCHAR(20),
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    DOB VARCHAR(20),
    ROLE VARCHAR(50),
    HIGHEST_T20I_RUNS VARCHAR(20)
);

--SELECT * FROM #SOURCE;

--SELECT * FROM CRICKETER_DETAIL;

MERGE CRICKETER_DETAIL AS T 
USING #SOURCE AS S
ON T.ID = S.ID
WHEN MATCHED
	THEN 
		UPDATE	
		SET
			T.FIRST_NAME = S.FIRST_NAME,
			T.LAST_NAME = S.LAST_NAME,
			T.DOB = S.DOB,
			T.ROLE = S.ROLE,
			T.HIGHEST_T20I_RUNS = S.HIGHEST_T20I_RUNS
WHEN NOT MATCHED
	THEN 
		INSERT (FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
		VALUES (S.FIRST_NAME,S.LAST_NAME,S.DOB,S.ROLE,S.HIGHEST_T20I_RUNS)
WHEN NOT MATCHED BY SOURCE
	THEN
		DELETE;





SELECT * FROM CRICKETER_DETAIL;