--PART:1 DATABASE CREATE
CREATE DATABASE Trigger_DB;

USE Trigger_DB;

--PART:2 TABLE CREATE
CREATE TABLE CRICKETER_DETAIL(
    CDID INT IDENTITY(1,1) PRIMARY KEY,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    DOB DATE,
    ROLE VARCHAR(50),
    HIGHEST_T20I_RUNS INT,
	CREATEDAT DATETIME DEFAULT GETDATE()
);

--PART:3 TWO ROW DATA INSERT
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('ROHIT','SHARMA','1987-04-30','Batter',121)

INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('VIRAT','KOHLI','1988-11-05','Batter',122)

--PART:4 DATA GET
SELECT * FROM CRICKETER_DETAIL;


--PART:5 
--UPDATEDAT COLUMN MISSING TABLE CREATE TIME SO NOW ADD THIS COLUMN

ALTER TABLE CRICKETER_DETAIL
ADD UPDATEDAT DATETIME;

--PART:6 NOW CDID = 1 --> HIGHEST_T20I_RUNS UPDATE 150
UPDATE CRICKETER_DETAIL
SET HIGHEST_T20I_RUNS = 150
WHERE CDID = 1;

--PART:7 
/*
ONLY HIGHEST_T20I_RUNS UPDATE WHEN UPDATE QUERY RUN 
BUT UPDATEDAT COLUMN STILL NULL 
SO NOW MY REQUIREMENT WHENEVER UPDATE  QUERY RUN UPDATEDAT
COLUMN UPDATE AUTO SO USE TRIGGER
*/

--PART:8
CREATE TRIGGER TRG_CRICKETER_DETAIL_UPDATEDAT
ON CRICKETER_DETAIL
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE C
    SET UPDATEDAT = GETDATE()
    FROM CRICKETER_DETAIL C
    INNER JOIN INSERTED I
        ON C.CDID = I.CDID;
		
	PRINT 'TRIGGER FIRED: TRG_CRICKETER_DETAIL_UPDATEDAT.'
END;

--PART:9 NOW CDID = 1 --> HIGHEST_T20I_RUNS UPDATE 200
UPDATE CRICKETER_DETAIL
SET HIGHEST_T20I_RUNS = 200
WHERE CDID = 1;

--PART:10 Inserted and Deleted Tables in SQL Server
/*
Inserted and Deleted tables in SQL Server are temporary, system-generated tables used inside triggers.
*/

--PART:11 INSERT TRIGGER FOR Inserted and Deleted Tables
CREATE TRIGGER TRG_INSERT_ON_CRICKETER_DETAIL
ON CRICKETER_DETAIL
AFTER INSERT
AS
BEGIN 
	SET NOCOUNT ON;
	
	SELECT 'INSERTED',* FROM INSERTED;
	SELECT 'DELETED',* FROM DELETED;
	
	PRINT 'TRIGGER FIRED: TRG_INSERT_ON_CRICKETER_DETAIL.'

END;
--GO

--NOW INSERT DATA 
INSERT INTO CRICKETER_DETAIL 
(FIRST_NAME, LAST_NAME, DOB,ROLE, HIGHEST_T20I_RUNS)
VALUES
('Yuvraj','Singh','1981-12-12', 'All-Rounder',77),
('Gautam','Gambhir','1981-10-14', 'Batsman',75),
('Virender','Sehwag','1978-10-20', 'Batsman',68),
('Ajinkya','Rahane','1988-06-06', 'Batsman',61),
('Shikhar','Dhawan','1985-12-05', 'Batsman',92),
('KL','Rahul','1992-04-18', 'Wicketkeeper-Batsman',110);


--PART:12 UPDATE TRIGGER FOR Inserted and Deleted Tables
CREATE TRIGGER TRG_UPDATE_ON_CRICKETER_DETAIL
ON CRICKETER_DETAIL
AFTER UPDATE
AS
BEGIN 
	SET NOCOUNT ON;
	
	SELECT 'INSERTED',* FROM INSERTED;
	SELECT 'DELETED',* FROM DELETED;
	
	PRINT 'TRIGGER FIRED: TRG_UPDATE_ON_CRICKETER_DETAIL.'

END;
--GO

--NOW UPDATE DATA
UPDATE CRICKETER_DETAIL
SET HIGHEST_T20I_RUNS = 152
WHERE FIRST_NAME = 'KL' AND LAST_NAME = 'Rahul';


--PART:13 DELETE TRIGGER FOR Inserted and Deleted Tables
CREATE TRIGGER TRG_DELETE_ON_CRICKETER_DETAIL
ON CRICKETER_DETAIL
AFTER DELETE
AS
BEGIN 
	SET NOCOUNT ON;
	
	SELECT 'INSERTED',* FROM INSERTED;
	SELECT 'DELETED',* FROM DELETED;
	
	PRINT 'TRIGGER FIRED: TRG_DELETE_ON_CRICKETER_DETAIL.'

END;
--GO

--NOW DELETE DATA 
DELETE FROM CRICKETER_DETAIL
WHERE CDID NOT IN (1,2);

--PART:14 NOW ABOVE INSERT,UPDATE,DELETE TRIGGER DROP 

DROP TRIGGER TRG_INSERT_ON_CRICKETER_DETAIL;
DROP TRIGGER TRG_UPDATE_ON_CRICKETER_DETAIL;
DROP TRIGGER TRG_DELETE_ON_CRICKETER_DETAIL;


--PART:15 ONLY HIGHEST_T20I_RUNS COLUMN INSERT VALUE SO (TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_INSERT) TRIGGER FIRED
/*
	THIS TRIGGER DATA STORE TABLE: HIGHEST_T20I_RUNS_INSERT_LOG
*/
CREATE TABLE HIGHEST_T20I_RUNS_INSERT_LOG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CDID INT,
	HIGHEST_T20I_RUNS INT,
	CREATEDAT DATETIME DEFAULT GETDATE()
)


CREATE TRIGGER TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_INSERT
ON CRICKETER_DETAIL
AFTER INSERT 
AS
BEGIN 
	IF EXISTS(
		SELECT 1 
		FROM INSERTED
		WHERE HIGHEST_T20I_RUNS IS NOT NULL
	)
	BEGIN 
		PRINT 'TRIGGER FIRED: TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_INSERT.'
		
		INSERT INTO HIGHEST_T20I_RUNS_INSERT_LOG(CDID,HIGHEST_T20I_RUNS)
		SELECT CDID,HIGHEST_T20I_RUNS FROM INSERTED
	END
END

--BELOW ROW INSERT --> TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_INSERT --> FIRED
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('Yashasvi','Jaiswal','2001-12-28','Opening Batter',100)

--BELOW ROW INSERT --> TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_INSERT --> NOT FIRED
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE)
VALUES('Rinku','Singh','1997-10-12','Middle-order Batter')

--PART:16 ONLY HIGHEST_T20I_RUNS COLUMN UPDATE VALUE SO (TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE) TRIGGER FIRED
/*
	THIS TRIGGER DATA STORE TABLE: HIGHEST_T20I_RUNS_UPDATE_LOG
	VALUE CHANGE SO TRIGGER FIRED 
	SAME VALUE UPDATE SO NOT FIRED -- MY REQUIREMENT
*/
CREATE TABLE HIGHEST_T20I_RUNS_UPDATE_LOG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CDID INT,
	OLD_HIGHEST_T20I_RUNS INT,
	NEW_HIGHEST_T20I_RUNS INT,
	CREATEDAT DATETIME DEFAULT GETDATE()
)

CREATE TRIGGER TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE
ON CRICKETER_DETAIL
AFTER UPDATE 
AS
BEGIN 
	IF UPDATE(HIGHEST_T20I_RUNS) --HIGHEST_T20I_RUNS ONLY THIS COLUMN VALUE CHANGE SO THIS TRIGGER FIRED
	BEGIN 
		IF EXISTS(
			SELECT 1 
			FROM INSERTED AS I 
			INNER JOIN DELETED AS D 
			ON I.CDID = D.CDID 
			WHERE   (I.HIGHEST_T20I_RUNS <> D.HIGHEST_T20I_RUNS)
                OR (I.HIGHEST_T20I_RUNS IS NULL AND D.HIGHEST_T20I_RUNS IS NOT NULL)
                OR (I.HIGHEST_T20I_RUNS IS NOT NULL AND D.HIGHEST_T20I_RUNS IS NULL)
		)
		BEGIN 
			PRINT 'TRIGGER FIRED: TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE.'
			
			INSERT INTO HIGHEST_T20I_RUNS_UPDATE_LOG(CDID,OLD_HIGHEST_T20I_RUNS,NEW_HIGHEST_T20I_RUNS)
			SELECT I.CDID,D.HIGHEST_T20I_RUNS,I.HIGHEST_T20I_RUNS
			FROM INSERTED AS I 
			INNER JOIN DELETED AS D 
			ON I.CDID = D.CDID 
			WHERE    (I.HIGHEST_T20I_RUNS <> D.HIGHEST_T20I_RUNS)
                OR (I.HIGHEST_T20I_RUNS IS NULL AND D.HIGHEST_T20I_RUNS IS NOT NULL)
                OR (I.HIGHEST_T20I_RUNS IS NOT NULL AND D.HIGHEST_T20I_RUNS IS NULL)	
		END
	END
END

--BELOW ROW UPDATE --> TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE --> FIRED  
UPDATE CRICKETER_DETAIL 
SET HIGHEST_T20I_RUNS = 121
WHERE CDID = 1

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 1 --CDID = 1 HIGHEST_T20I_RUNS VALUE  CHANGE
SELECT * FROM HIGHEST_T20I_RUNS_UPDATE_LOG WHERE CDID = 1 --CDID = 1  LOG  INSERT


--BELOW ROW UPDATE --> TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE --> NOT FIRED --> BECAUSE FIRST_NAME Update
UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = 'Yashasvi Jaiswal'
WHERE CDID = 33

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 33  --CDID = 33 FIRST_NAME VALUE CHANGE
SELECT * FROM HIGHEST_T20I_RUNS_UPDATE_LOG WHERE CDID = 33--CDID = 33 NOT  LOG INSERT

--BELOW ROW UPDATE --> TRG_CRICKETER_DETAIL_HIGHEST_T20I_RUNS_UPDATE --> NOT FIRED -->BECAUSE SAME HIGHEST_T20I_RUNS
UPDATE CRICKETER_DETAIL 
SET HIGHEST_T20I_RUNS = 122
WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 2 --CDID = 2 HIGHEST_T20I_RUNS VALUE NOT  CHANGE
SELECT * FROM HIGHEST_T20I_RUNS_UPDATE_LOG WHERE CDID = 2 --CDID = 2  LOG NOT INSERT

 
--PART:17 INSERT DATA  
INSERT INTO CRICKETER_DETAIL(FIRST_NAME,LAST_NAME,DOB,ROLE,HIGHEST_T20I_RUNS)
VALUES('Axar','Patel','1994-01-20','All-rounder',65)

--PART:18
--NOW DELETE TRIGGER 
/*
	THIS TRIGGER DATA STORE TABLE:  CRICKETER_DETAIL ROW DELETE SO DATA ENTER DELETE_LOG TABLE
*/
CREATE TABLE DELETE_LOG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	COLUMN_LIST NVARCHAR(MAX),
	CREATEDAT DATETIME DEFAULT GETDATE()
)

CREATE TRIGGER TRG_CRICKETER_DETAIL_DELETE
ON CRICKETER_DETAIL
AFTER DELETE 
AS
BEGIN 
	PRINT 'TRIGGER FIRED: TRG_CRICKETER_DETAIL_DELETE.'
	
	INSERT INTO DELETE_LOG (COLUMN_LIST)
	SELECT (
		SELECT * 
		FROM DELETED
		FOR JSON PATH
	) AS COLUMN_LIST;
END

DELETE FROM CRICKETER_DETAIL WHERE CDID = 35;

--PART:19
--ANY COLUMN UPDATE 

CREATE TABLE CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CDID INT,
	COLUMNNAME VARCHAR(100),
	OLDVALUE VARCHAR(MAX), 
	NEWVALUE VARCHAR(MAX),
	CREATEDAT DATETIME DEFAULT GETDATE()
)


CREATE TRIGGER TRG_CRICKETER_DETAIL_ANY_COLUMN_UPDATE
ON CRICKETER_DETAIL
AFTER UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @sql NVARCHAR(MAX);

    -- Move pseudo tables
    SELECT * INTO #I FROM INSERTED;
    SELECT * INTO #D FROM DELETED;

    -- Build dynamic SQL safely
    SELECT @sql = '
    INSERT INTO CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG (CDID, COLUMNNAME, OLDVALUE, NEWVALUE)
    SELECT *
    FROM (
        ' + STRING_AGG(
            '
            SELECT 
                I.CDID,
                ''' + c.name + ''' AS COLUMNNAME,
                CONVERT(NVARCHAR(MAX), D.' + QUOTENAME(c.name) + ') AS OLDVALUE,
                CONVERT(NVARCHAR(MAX), I.' + QUOTENAME(c.name) + ') AS NEWVALUE
            FROM #I I
            JOIN #D D ON I.CDID = D.CDID
            ',
            ' UNION ALL '
        ) + '
    ) A
    WHERE ISNULL(OLDVALUE, '''') <> ISNULL(NEWVALUE, '''');
    '
    FROM sys.columns c
    WHERE c.object_id = OBJECT_ID('CRICKETER_DETAIL')
      AND c.name NOT IN ('CDID','CREATEDAT')
      AND c.is_computed = 0;

    -- DEBUG (optional)
    -- PRINT @sql;

    EXEC sp_executesql @sql;

    PRINT 'TRIGGER FIRED: TRG_CRICKETER_DETAIL_ANY_COLUMN_UPDATE.'

END;

UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = 'Rohit S'
WHERE CDID = 1;

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 1

SELECT * FROM CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG WHERE CDID = 1

UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = 'ROHIT'
WHERE CDID = 1


SELECT * FROM CRICKETER_DETAIL WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG WHERE CDID = 2


UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = 'Virat 18',HIGHEST_T20I_RUNS=122
WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG WHERE CDID = 2


UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = NULL
WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG WHERE CDID = 2


UPDATE CRICKETER_DETAIL 
SET FIRST_NAME = 'VIRAT'
WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL WHERE CDID = 2

SELECT * FROM CRICKETER_DETAIL_ANY_COLUMN_UPDATE_LOG WHERE CDID = 2
